added discord webhook

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Validate code syntax
-        run: npx lint-staged || echo "::error::Code validation failed. See workflow logs for details." && exit 1
+        run: npx lint || echo "::error::Code validation failed. See workflow logs for details." && exit 1
 
   build:
     name: Build
