exit on error commands added in yaml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -39,7 +39,9 @@ jobs:
       - name: Install dependencies
         run: npm ci
       - name: Run tests
-        run: npm test || exit 1  # Exit with status code 1 if tests fail
+        run: |
+          npm test
+          if [ $? -ne 0 ]; then exit 1; fi  # Exit with status code 1 if tests fail
 
   deploy:
     name: Deploy
@@ -64,7 +66,6 @@ jobs:
     name: Notify on Failure and Success
     runs-on: ubuntu-latest
     needs: [validate-code, test, deploy]
-    if: always() # Trigger on both success and failure
     steps:
       - name: Notify on Failure
         if: failure()
